### ISSUE TITLE
[8] Review all requests to ensure includes & fields are specified

### ISSUE THREAD

**Issue by ryantownsend** [shiftcommerce/shift-node-api#26]
Raising this based on @mufudzimasaire's PR #25 due to missing includes/fields params on API calls causing breakages.

### User Stories

As an API consumer, I want to receive only the data I require from the API, in order to lower CPU and memory consumption and therefore improving performance.

As a SHIFT developer, I want consumers of the API to specify the exact includes and fields they need, in order to know I can release changes without breaking websites/integrations.

### Acceptance Criteria

- [ ] All methods for calling the API have an option for supplying `includes` and `fields` parameters for the request
- [ ] HTTP requests to the API must always have a `fields` parameter, `includes` is optional – these fields should either be defaulted in the library or throw an error if not supplied

**Comment by Azfletch** [comment]
completed in above PRs
